### ISSUE TITLE
HDMI? 

### ISSUE THREAD

**Issue by InstantNo0dle** [cyberos/other-issues#12]
Is there a way to get HDMI working on cyber os? I mainly use my laptop connected to an external monitor so not having HDMI would be a huge deal breaker for me. Any suggestions for how I would be able to use HDMI would be much appreciated.

**Comment by omaemae** [comment]
you can use xrandr (`xorg-xrandr` package) or, if you prefer a graphical interface, arandr (`arandr` package)

if you're using GDM, it should automatically pick up the HDMI monitor, but i'm assuming you're using LightDM

if you're using LightDM, you can add this to your `[Seat:*]` config:
```
display-setup-script=xrandr --output LVDS1 --off --output HDMI1 --primary --mode 1920x1080 --pos 0x0 --rotate normal
```
make sure to tweak it to your needs!

**Comment by InstantNo0dle** [comment]
Thank you!
