### ISSUE TITLE
Possible things to add

### ISSUE THREAD

**Issue by rounk-ctrl** [cyberos/other-issues#2]
These things the DE needs:
* A Text Editor
* A Terminal
* A System Monitor (preferable)
* A Date&Time Applet (which pops out when you click the time)
* A Pop-up battery applet (instead of opening settings)

**Comment by YeaToast** [comment]
UXTerm can be used until a terminal is created

**Comment by rounk-ctrl** [comment]
But native?

**Comment by omaemae** [comment]
> Text editor
VSCode will do fine for now
> Terminal
was thinking about using QmlTerminalWidget
> System Monitor
i don't know, htop is pretty nice on its onw
> Date and time
yeah that'd be nice
> popup battery applet
not really nice

**Comment by rounk-ctrl** [comment]
whats special in a full screen battery meter?

**Comment by omaemae** [comment]
> whats special in a full screen battery meter?

@rounk-ctrl you suggested it, you tell me

**Comment by rounk-ctrl** [comment]
a popup one is much better, for taking a quick look at how much time remaining?

**Comment by omaemae** [comment]
you can hover over it and it'll tell you the current battery status
![image](https://user-images.githubusercontent.com/17727163/102229317-eed36480-3eeb-11eb-8a89-85eda569da14.png)

**Comment by rounk-ctrl** [comment]
or add a how much time remaining?

**Comment by omaemae** [comment]
![image](https://user-images.githubusercontent.com/17727163/102229622-4eca0b00-3eec-11eb-915c-e763aded0242.png)

**Comment by rounk-ctrl** [comment]
maybe battery popup is useless

**Comment by YeaToast** [comment]
Macs have battery life indicators, why not add that too

**Comment by omaemae** [comment]
We have a maximum capacity indicator in Settings. Would be useless to add it to the popup, though.

**Comment by rekols** [comment]
> or add a how much time remaining?

Left click on the battery icon on the StatusBar to jump to the settings window.

![Screenshot from 2020-12-16 14-30-35](https://user-images.githubusercontent.com/9636382/102313328-62887680-3fab-11eb-89bb-eb4ce5ab8ca4.png)
