### ISSUE TITLE
Wayland plan

### ISSUE THREAD

**Issue by rekols** [cyberos/other-issues#3]
We need to switch from X to Wayland. Do you have any ideas?

@felixonmars 
@probonopd 
@omaemae 
@Z-bin

**Comment by probonopd** [comment]
Why do you think we _need_? 

[Think twice before abandoning Xorg. Wayland breaks everything!](https://gist.github.com/probonopd/9feb7c20257af5dd915e3a9f2d1f2277)

**Comment by felixonmars** [comment]
I am not fond of wayland in any way. So no I won't be working on this.

**Comment by omaemae** [comment]
I also think we don't need Wayland. Xorg is fine.
