### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by omaemae** [cyberos/other-issues#5]
I think we can work on translations for Cyber. If we can add translation support to Cyber, we can open up accessibility to people who don't understand English.

We can reference the following code for using Qt translations with CMake: https://gist.github.com/02JanDal/70a39f2cc3d2002b3588 https://gist.github.com/giraldeau/546ba5512a74dfe9d8ea0862d66db412

What do you guys think? @rekols @probonopd @felixonmars @ChungZH

**Comment by rekols** [comment]
YUP

**Comment by rekols** [comment]
Settings: https://github.com/cyberos/cyber-settings/commit/fd02f26a4b1cee06d7bf21b6d694bd7ae754c0dc

**Comment by rekols** [comment]
This is my way, first generate the TS file of the original language(English)

```
mkdir translations
lupdate ./src -ts ./translations/en_US.ts
```

Then generate the target language you want to translate, such as Chinese: `lupdate ./src -ts ./translations/zh_CN.ts`

cmake:

```cmake
....
file(GLOB TS_FILES translations/*.ts)
qt5_create_translation(QM_FILES ${TS_FILES})
add_custom_target(translations DEPENDS ${QM_FILES} SOURCES ${TS_FILES})
add_dependencies(${PROJECT_NAME} translations)
......
install(FILES ${QM_FILES} DESTINATION /usr/share/${PROJECT_NAME}/translations)

```

CPP:

```c++
QLocale locale;
QString qmFilePath = QString("%1/%2.qm").arg("/usr/share/cyber-settings/translations/").arg(locale.name());
if (QFile::exists(qmFilePath)) {
    QTranslator *translator = new QTranslator(QGuiApplication::instance());
    if (translator->load(qmFilePath)) {
        QGuiApplication::installTranslator(translator);
    } else {
        translator->deleteLater();
    }
}
```

**Comment by probonopd** [comment]
For helloSystem, I am currently looking whether we can use https://hosted.weblate.org/, maybe it would be useful for this project too?

**Comment by omaemae** [comment]
> For helloSystem, I am currently looking whether we can use https://hosted.weblate.org/, maybe it would be useful for this project too?

@probonopd That looks like a good idea. I'll leave the final decision to @rekols.

**Comment by rekols** [comment]
Of course, we have to use this kind of translation platform, but I don't know how to choose. Let's see what other open source communities use.

**Comment by rekols** [comment]
https://hosted.weblate.org/projects/cyberos/cyber-settings/

**Comment by rekols** [comment]
I have added weblate to settings.

**Comment by ChungZH** [comment]
我一登进去就能修改翻译了，有没有什么审查机制的呀 😹

======

I can even modify the translation. Is there any review mechanism

**Comment by omaemae** [comment]
@ChungZH We only have pull requests, currently we have no review mechanism, since we don't know all the languages in the world of course. Weblate seems to be misconfigured right now.

**Comment by ChungZH** [comment]
We can use https://crowdin.com/ too. He is strong too 💪

**Comment by ChungZH** [comment]
https://crowdin.com/ is good too 💪

**Comment by omaemae** [comment]
> https://crowdin.com/ is good too

It sounds good. What do you guys think? @rekols @probonopd

**Comment by rekols** [comment]
> > https://crowdin.com/ is good too
> 
> It sounds good. What do you guys think? @rekols @probonopd

I'll try it now

**Comment by rekols** [comment]
Let's use https://hosted.weblate.org/

**Comment by omaemae** [comment]
Yeah, let's use Weblate. Seems like Crowdin tried erasing already existing translations.

**Comment by rekols** [comment]
@probonopd I want to know how you change the file mask in weblate? I have a strange phenomenon here: Ru_ Ru becomes Ru, zh_ CN becomes zh_ Hans

**Comment by omaemae** [comment]
@rekols You might want to fix the Dock push issues.
![image](https://user-images.githubusercontent.com/17727163/108097975-1dec8a80-7083-11eb-85a7-90651937eed4.png)

**Comment by rekols** [comment]
> You might want to fix the Dock push issues.

The problem of file name error has not been solved yet

**Comment by omaemae** [comment]
> I have a strange phenomenon here: Ru_ Ru becomes Ru, zh_ CN becomes zh_ Hans

`ru_RU` -> `ru` seems normal to me, since Russian is used only in Russia (including the [Kaliningrad Oblast](https://en.wikipedia.org/wiki/Kaliningrad_Oblast)), and Qt is fine handling it both as `ru` and `ru_RU` anyway.
![image](https://user-images.githubusercontent.com/17727163/108099335-c0f1d400-7084-11eb-8262-b20d47e81581.png)


`zh_CN` -> `zh_Hans` makes no sense to me, but Qt is fine handling both as well. 
![image](https://user-images.githubusercontent.com/17727163/108099389-d404a400-7084-11eb-8b3f-88d0775e174f.png)

I think we can dismiss it @rekols.

**Comment by rekols** [comment]
This is because the correct Chinese name QM file has been installed in the settings, You can test it. Change the cyber FM to Chinese.

**Comment by probonopd** [comment]
Hi @rekols 

On https://hosted.weblate.org/settings/cyberos/cyber-dock/#vcs enter:

* Source code repository: `https://github.com/cyberos/cyber-dock`
* Repository push URL: `git@github.com:cyberos/cyber-dock.git`
* Push branch: empty
* Repository browser: empty

On https://github.com/cyberos/cyber-dock/settings/access add the user `weblate` and give it __Write__ rights

Then it should work

**Comment by omaemae** [comment]
> This is because the correct Chinese name QM file has been installed in the settings, You can test it. Change the cyber FM to Chinese.

Huh, you're right. It doesn't work. Weird...

**Comment by omaemae** [comment]
> On https://hosted.weblate.org/settings/cyberos/cyber-dock/#vcs enter:
> 
> * Source code repository: `https://github.com/cyberos/cyber-dock`
> * Repository push URL: `git@github.com:cyberos/cyber-dock.git`
> * Push branch: empty
> * Repository browser: empty
> 
> On https://github.com/cyberos/cyber-dock/settings/access add the user `weblate` and give it **Write** rights
> 
> Then it should work. It took me a while to find it out.

I think he knows, since the same happened in Settings before and now it works fine.

**Comment by rekols** [comment]
@probonopd  I've solved the problem of permissions, and now I have another problem.

**Comment by probonopd** [comment]
> I want to know how you change the file mask in weblate? I have a strange phenomenon here: Ru_ Ru becomes Ru, zh_ CN becomes zh_ Hans

I don't know the answer to this, sorry.

**Comment by omaemae** [comment]
> I've solved the problem of permissions, and now I have another problem.

@rekols Doesn't look solved to me, really. 
![image](https://user-images.githubusercontent.com/17727163/108107037-fdc2c880-708e-11eb-939b-82bbeed6bc72.png)

**Comment by rekols** [comment]
First solve the file name and then solve the permissions, after all, now the translation is wrong.

**Comment by omaemae** [comment]
Yes, I guess that's true. I'll try researching this on my own.

**Comment by omaemae** [comment]
@rekols @probonopd I believe you can change the format for the filenames. If we can't, then we can try [renaming the file ourselves](https://github.com/WeblateOrg/weblate/issues/2559#issuecomment-464502742).

`zh-Hant` seems to be a newer format, expressing the macrolanguage (Chinese `zh`) and the subscript (Traditional `Hant`). You can read more here: https://www.w3.org/International/articles/bcp47/

It seems that Linux/glibc/gettext/Qt doesn't like this change.

**Comment by omaemae** [comment]
> Any reason not to use the more standard glibc locale name: zh_CN?
> I don't think glibc (or gettext) knows about zh_Hans, let alone zh-Hans.
> zh-Hans is a CLDR locale name.

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/JFT4PHJMO7HX6BLVHQNEBAQQ3S6DGHPP/

@probonopd @rekols

**Comment by omaemae** [comment]
Can we make Weblate respect [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1) and [ISO 3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) by default?

**Comment by probonopd** [comment]
Possibly a question for https://github.com/WeblateOrg/weblate/issues/ in case their documentation does not contain any information regarding this.

**Comment by omaemae** [comment]
I couldn't find anything in the user documentaton, only in the administrator documentation which seems to be tailored towards self-hosted instances. Would you mind making the issue at Weblate? @probonopd 

For now, [we can rename the files ourselves manually when we need to](https://github.com/WeblateOrg/weblate/issues/2559#issuecomment-464502742). @rekols

**Comment by windowsboy111** [comment]
Quick note --
### Weblate breaks really badly, there are **2 sets of Chinese Traditional translations** in the languages list, **2 sets for Chinese Simplified** and **2 sets of Cantonese** (Yue) translations.
Since Weblate do not provide any support for Cantonese translations, (after talking with omaemae)
- Cantonese translations will be provided via git/pr
- `zh_TW` for Traditional, `zh_CN` for Simplified, `zh_HK` for Cantonese

However darksunlight suggests to use `zh_Hant-TW` and `zh_Hant-HK` respectively so I am not so sure which one to use.
I lately find out that Cantonese in Arch Linux is `yue_HK` so this makes things more complicated than it should be.

#### What do you guys think?
I'd say I prefer `zh_CN` and `zh_TW` because of backwards compatibility and not to mess up weblate.

**Comment by omaemae** [comment]
@windowsboy111 We know about this issue already. The workaround for now is to manually change the filename.

**Comment by rekols** [comment]
> Can we make Weblate respect [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1) and [ISO 3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) by default?

No, it seems that it cannot be changed, and I did not find a place to change it.

**Comment by omaemae** [comment]
@rekols We figured out that [we can rename the files in our repos manually, and Weblate will read the change, and will leave it, correctly.](https://github.com/WeblateOrg/weblate/issues/2559#issuecomment-464502742) We can reopen the Weblate translations in my opinion.

**Comment by rekols** [comment]
> @rekols We figured out that [we can rename the files in our repos manually, and Weblate will read the change, and will leave it, correctly.](https://github.com/WeblateOrg/weblate/issues/2559#issuecomment-464502742) We can reopen the Weblate translations in my opinion.

Means do we need to rename it manually?

**Comment by rekols** [comment]
I think we should not waste time on the weblate.

**Comment by omaemae** [comment]
> > @rekols We figured out that [we can rename the files in our repos manually, and Weblate will read the change, and will leave it, correctly.](https://github.com/WeblateOrg/weblate/issues/2559#issuecomment-464502742) We can reopen the Weblate translations in my opinion.
> 
> Means do we need to rename it manually?

And Weblate will automatically pick up the change and follow it, correct.

**Comment by windowsboy111** [comment]
From my understanding weblate created those duplicated Chinese translation because of the `zh_Hant_Hant.ts` joke, so yeah if we unify all to like `zh_HK` `zh_TW` and `zh_CN` and remove the duplicated ones it should work fine.

**Comment by omaemae** [comment]
Yes, that's also my understanding of this.

Shame that you deleted the Weblate page already @rekols, we had a pretty good start. :(

**Comment by windowsboy111** [comment]
Do you fancy Weblate? I think we can recreate that Weblate page. Having people that doesn't have any `git` knowledges from TFT contributing different translations is a much more efficient way to do things.

---

想不想要Weblate？我覺得可以重新整Weblate出來，始終在 The Flying Tech (Discord server) 裡面不懂`git`的人也可以翻譯，不會加快效率嗎？

**Comment by omaemae** [comment]
@windowsboy111 Weblate is pretty cool, yes. I already submitted some Polish translations for @probonopd's helloSystem.

**Comment by rekols** [comment]
I have come up with a way to generate all TS format files with script, and then synchronize them with weblate, which can recognize them.

**Comment by omaemae** [comment]
@rekols Are we getting Weblate back? Or have you missed a "to" in "I have *to* come up [...]"?

If it's the latter, we can make a bash script with an array of supported languages (mainly including problematic ones such as `ru-RU` and `zh-CN`), then generate them with a for-loop:
```sh
for ts in ./translations/${langs[@]}.ts; do
    lupdate . -ts $ts
done
```

We can reuse the same for-loop for mass-updating the translations:
```sh
for ts in ./translations/*.ts; do
    lupdate . -ts $ts
done
```

**Comment by rekols** [comment]
@omaemae I think it's up to you.

**Comment by omaemae** [comment]
@rekols Weblate will be really helpful for us as we don't have to handle pull requests constantly.

I don't think I can even set up Weblate since I don't have access to the organization settings anymore.

**Comment by rekols** [comment]
> @rekols Weblate will be really helpful for us as we don't have to handle pull requests constantly.
> 
> I don't think I can even set up Weblate since I don't have access to the organization settings anymore.

allright, tray agin.

**Comment by omaemae** [comment]
I'll work on it tomorrow, it's 12 AM here.

**Comment by ChungZH** [comment]
> > @rekols Weblate will be really helpful for us as we don't have to handle pull requests constantly.
> > I don't think I can even set up Weblate since I don't have access to the organization settings anymore.
> 
> allright, tray again.

~~try~~

**Comment by omaemae** [comment]
@rekols Done setting up. https://hosted.weblate.org/projects/cyberos/

I found a way to mitigate the `ru_RU` -> `ru` problem: 
![image](https://user-images.githubusercontent.com/17727163/108486448-6207a700-729e-11eb-8352-d3c202d07922.png)

As for `zh_CN` -> `zh_Hans`, manual editing upstream does the trick:
![image](https://user-images.githubusercontent.com/17727163/108486547-7a77c180-729e-11eb-8719-3b94ba4e173b.png)

**Comment by ChungZH** [comment]
oh sorry.....
So exciting
我能继续为 cyberos 发光发热了

**Comment by windowsboy111** [comment]
bruh

**Comment by windowsboy111** [comment]
how tf did you click the wrong button and close this

also you basically spammed my email notification

**Comment by omaemae** [comment]
Please continue conversation in #7. :)
